sre-test:
  image: ${TRIGGER_IMAGE}
  stage: test
  when: manual
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - echo ${CI_COMMIT_TITLE}
    - |
      curl -i --header "Content-Type: application/json" \
      --request POST \
      --data '{
          "key": "'${MLHUB_TRIGGER_KEY}'",
          "job_name": "Bonito SRE: '${CI_COMMIT_REF_NAME}' - '"$CI_COMMIT_TITLE"' ",
          "script_parameters": {
              "bonito_version":"'${CI_COMMIT_SHA}'",
              "sre_output":"'${SRE_OUTPUT_ROOT}'/'${CI_COMMIT_SHA}'/",
              "models":["dna_r10.4.1_e8.2_400bps_fast@v4.0.0","dna_r10.4.1_e8.2_400bps_hac@v4.0.0","dna_r10.4.1_e8.2_400bps_sup@v4.0.0"],
              "validation_set_path":"'${SRE_OUTPUT_ROOT}'/validation_sets",
              "validation_data_type":"prom"
          }
      }' \
      ${MLHUB_TRIGGER_URL}
